from app.core.reports import CandidateMove, MoveCoachingReport
from app.core.services import ReviewService


def test_build_review_surfaces_missed_priority():
    review = ReviewService().review_reports(
        [
            MoveCoachingReport(
                board_fen="",
                move_number=4,
                player_color="White",
                chosen_move=CandidateMove(
                    san="h3",
                    uci="h2h3",
                    score_cp=-20,
                    eval_gap_cp=120,
                    tutor_score=10.0,
                    difficulty=1.5,
                    tactical_risk_score=12.0,
                    strategic_fit_score=2.0,
                    human_plausibility_score=45.0,
                    mistake_class="inaccuracy",
                    primary_theme="development",
                    primary_reason="Missed development.",
                    player_friendly_explanation="Missed development.",
                    training_habit="Develop pieces first.",
                    better_alternative_reason="Nf3 develops cleanly.",
                ),
                engine_best_move=CandidateMove(
                    san="Nf3",
                    uci="g1f3",
                    score_cp=100,
                    eval_gap_cp=0,
                    tutor_score=95.0,
                    difficulty=0.8,
                    tactical_risk_score=0.0,
                    strategic_fit_score=40.0,
                    human_plausibility_score=90.0,
                    mistake_class="best",
                    primary_theme="development",
                    primary_reason="Develops naturally.",
                    player_friendly_explanation="Develops naturally.",
                    training_habit="Develop pieces first.",
                    better_alternative_reason="Already best.",
                ),
                tutor_move=CandidateMove(
                    san="Nf3",
                    uci="g1f3",
                    score_cp=100,
                    eval_gap_cp=0,
                    tutor_score=95.0,
                    difficulty=0.8,
                    tactical_risk_score=0.0,
                    strategic_fit_score=40.0,
                    human_plausibility_score=90.0,
                    mistake_class="best",
                    primary_theme="development",
                    primary_reason="Develops naturally.",
                    player_friendly_explanation="Develops naturally.",
                    training_habit="Develop pieces first.",
                    better_alternative_reason="Already best.",
                ),
                eval_before_cp=100,
                eval_after_cp=-20,
                score_delta_cp=120,
                verdict="Inaccuracy",
                coach_note="Primary coaching goal: address development first.",
                lesson="Missed development.",
            ),
            MoveCoachingReport(
                board_fen="",
                move_number=8,
                player_color="White",
                chosen_move=CandidateMove(
                    san="a3",
                    uci="a2a3",
                    score_cp=-80,
                    eval_gap_cp=180,
                    tutor_score=4.0,
                    difficulty=1.7,
                    tactical_risk_score=28.0,
                    strategic_fit_score=2.0,
                    human_plausibility_score=30.0,
                    mistake_class="blunder",
                    primary_theme="king_safety",
                    primary_reason="Missed king safety.",
                    player_friendly_explanation="Missed king safety.",
                    training_habit="Castle before side pawn moves.",
                    better_alternative_reason="O-O makes the king safer.",
                ),
                engine_best_move=CandidateMove(
                    san="O-O",
                    uci="e1g1",
                    score_cp=100,
                    eval_gap_cp=0,
                    tutor_score=96.0,
                    difficulty=0.6,
                    tactical_risk_score=0.0,
                    strategic_fit_score=45.0,
                    human_plausibility_score=93.0,
                    mistake_class="best",
                    primary_theme="king_safety",
                    primary_reason="Castles to safety.",
                    player_friendly_explanation="Castles to safety.",
                    training_habit="Castle before side pawn moves.",
                    better_alternative_reason="Already best.",
                ),
                tutor_move=CandidateMove(
                    san="O-O",
                    uci="e1g1",
                    score_cp=100,
                    eval_gap_cp=0,
                    tutor_score=96.0,
                    difficulty=0.6,
                    tactical_risk_score=0.0,
                    strategic_fit_score=45.0,
                    human_plausibility_score=93.0,
                    mistake_class="best",
                    primary_theme="king_safety",
                    primary_reason="Castles to safety.",
                    player_friendly_explanation="Castles to safety.",
                    training_habit="Castle before side pawn moves.",
                    better_alternative_reason="Already best.",
                ),
                eval_before_cp=100,
                eval_after_cp=-80,
                score_delta_cp=180,
                verdict="Blunder risk",
                coach_note="Primary coaching goal: address king safety first.",
                lesson="Missed king safety.",
            ),
        ],
        "[Event \"Test\"]\n*",
    )
    assert any("recurring pattern" in finding.lower() for finding in review.findings)
    assert "main lesson" in review.summary.lower()
