"""
Load and serve learned Bayesian model parameters.

Provides a clean interface for other modules (move_engine, diagnostics, levels)
to access the posterior means from the trained models.  Falls back to None
when the parameter file has not been generated yet, allowing the rest of the
system to use the original heuristic weights.

Parameter file: data/trained_models/learned_params.json
Generated by:  notebooks/model_training.ipynb
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path

# Path to the learned parameters JSON, relative to the chess_tutor/ root
_PARAMS_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "data", "trained_models", "learned_params.json",
)


@dataclass(frozen=True)
class MoveChoiceParams:
    """Learned coefficients for predicting human move choices (Model A)."""
    coefficients: dict[str, float]
    intercept: float


@dataclass(frozen=True)
class TutorScoreParams:
    """Learned weights for tutor score computation (Model B)."""
    weights: dict[str, float]
    intercept: float


class LearnedParamsStore:
    """
    Singleton-style store for learned model parameters.

    On first access, attempts to load from the JSON file.  If the file
    does not exist (e.g. models have not been trained yet), all lookups
    return None so callers can fall back to heuristic defaults.
    """

    def __init__(self) -> None:
        self._raw: dict | None = None
        self._loaded = False

    def _ensure_loaded(self) -> None:
        """Lazy-load the parameter file once."""
        if self._loaded:
            return
        self._loaded = True
        if os.path.exists(_PARAMS_PATH):
            with open(_PARAMS_PATH) as fh:
                self._raw = json.load(fh)

    def get_move_choice_params(self, elo_band: str) -> MoveChoiceParams | None:
        """
        Get Model A (human move prediction) coefficients for an ELO band.

        Args:
            elo_band: One of "600", "1000", "1400", "1800".

        Returns:
            MoveChoiceParams or None if not available.
        """
        self._ensure_loaded()
        if self._raw is None:
            return None
        band_data = self._raw.get("model_a", {}).get(elo_band)
        if band_data is None:
            return None
        return MoveChoiceParams(
            coefficients=band_data["coefficients"],
            intercept=band_data["intercept"],
        )

    def get_tutor_score_params(self, elo_band: str) -> TutorScoreParams | None:
        """
        Get Model B (tutor score weight) parameters for an ELO band.

        Args:
            elo_band: One of "600", "1000", "1400", "1800".

        Returns:
            TutorScoreParams or None if not available.
        """
        self._ensure_loaded()
        if self._raw is None:
            return None
        band_data = self._raw.get("model_b", {}).get(elo_band)
        if band_data is None:
            return None
        return TutorScoreParams(
            weights=band_data["weights"],
            intercept=band_data["intercept"],
        )

    def is_available(self) -> bool:
        """Check whether learned parameters have been loaded."""
        self._ensure_loaded()
        return self._raw is not None


# Module-level singleton
learned_params = LearnedParamsStore()
